### ISSUE TITLE
Can not find anything

### ISSUE THREAD

**Issue by alr86** [p-nerd/sr.nvim#9]
Plugin isn't find anything for me:

https://github.com/user-attachments/assets/9df4763a-c1ce-4f7f-9c5b-781849fe99a7

**Comment by mt-shihab26** [comment]
Please show me the current working directory. This plugin ignores the files that are put on the .gitginore file. Also, please show me your .gitignore file. If you have a file tree like neo-tree you can send me your file tree screenshot or ls -a on the current working directory.

**Comment by mt-shihab26** [comment]
We can make this plugin work as we expect. Another feature we can add will be the current buffer if it is git ignore or not. if it is open then it will search on the current buffer. Suggest to me if it is a good idea or not.

**Comment by alr86** [comment]
> Please show me the current working directory. This plugin ignores the files that are put on the .gitginore file.

It's not a project managed with Git, it's my rEFInd configuration in /boot drive, rEFInd is a bootloader similar to GRUB.

![image](https://github.com/user-attachments/assets/4600c76d-4d42-48a8-a029-cdaa6be6cd83)

**Comment by alr86** [comment]
Also I have same issue with ~/Untitled.txt
